# Generated by Django 3.0 on 2019-12-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_goods_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='phone',
            field=models.CharField(default='b', max_length=20),
        ),
        migrations.AddField(
            model_name='goods',
            name='username',
            field=models.CharField(default='a', max_length=20),
        ),
    ]
