# Generated by Django 3.0 on 2019-12-08 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20191208_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='date',
        ),
    ]
