# Generated by Django 3.0 on 2019-12-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_remove_goods_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='push_date',
            field=models.DateField(auto_now=True),
        ),
    ]
