# Generated by Django 3.0 on 2019-12-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_goods_push_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='push_date',
            field=models.DateField(),
        ),
    ]
