# Generated by Django 3.0 on 2019-12-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20191208_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
