# Generated by Django 3.0 on 2019-12-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20191208_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='push_date',
            field=models.DateField(auto_now=True),
        ),
    ]
