# Generated by Django 3.0 on 2019-12-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_auto_20191208_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='cate',
            field=models.CharField(choices=[('tech', '电子数码'), ('dianqi', '家用电器'), ('service', '技能服务'), ('cloths', '服饰鞋子'), ('life', '生活日用'), ('book', '图书'), ('other', '其他')], default='其他', max_length=32),
        ),
    ]
