# Generated by Django 3.0 on 2019-12-10 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_goods_cate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
